// src/components/InboxScreen.vue
<template>
  <div>
    <div v-if="isError" class="page lists-show">
      <div class="wrapper-message">
        <span class="icon-face-sad" />
        <p class="title-message">Oh no!</p>
        <p class="subtitle-message">Something went wrong</p>
      </div>
    </div>
    <div v-else class="page lists-show">
      <nav>
        <h1 class="title-page">Taskbox</h1>
      </nav>
      <TaskList />
    </div>
  </div>
</template>
<script lang="ts" setup>
import { computed } from 'vue'

import { useTaskStore } from '../store'

import TaskList from './TaskList.vue'

//👇 Creates a store instance
const store = useTaskStore()
// 👇 Fetches tasks for the store
store.fetchTasks()

//👇 Retrieves the error from the store's state
const isError = computed(() => store.status === 'failed')
</script>

// src/app/components/inbox-screen.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnInit, computed } from '@angular/core';

import { Store } from '../state/store';

import { TaskListComponent } from './task-list.component';

@Component({
  selector: 'app-inbox-screen',
  standalone: true,
  imports: [CommonModule, TaskListComponent],
  template: `
    <div *ngIf="isError()" class="page lists-show">
      <div class="wrapper-message">
        <span class="icon-face-sad"></span>
        <p class="title-message">Oh no!</p>
        <p class="subtitle-message">Something went wrong</p>
      </div>
    </div>

    <div *ngIf="!isError()" class="page lists-show">
      <nav>
        <h1 class="title-page">Taskbox</h1>
      </nav>
      <app-task-list></app-task-list>
    </div>
  `,
})
export class InboxScreenComponent implements OnInit {
  store = inject(Store);

  isError = computed(() => this.store.status() === 'error');

  ngOnInit(): void {
    this.store.fetchTasks();
  }
}
