// src/components/InboxScreen.tsx
import { useMemo } from "react";

import TaskList from "./TaskList";
import { getFormattedDate } from "#utils/date";
import { useTasks } from "#lib/useTasks.ts";

export default function InboxScreen() {
  const { error, tasks, updateTaskState, status } = useTasks();
  
  const today = useMemo(() => getFormattedDate(new Date()), []);

  if (error) {
    return (
      <div className="page lists-show">
        <div className="wrapper-message">
          <span className="icon-face-sad" />
          <p className="title-message">Oh no!</p>
          <p className="subtitle-message">Something went wrong</p>
        </div>
      </div>
    );
  }
  return (
    <div className="page lists-show">
      <nav>
        <h1 className="title-page">Taskbox - {today}</h1>
      </nav>
      <TaskList tasks={tasks} updateTaskState={updateTaskState} status={status}/>
    </div>
  );
}

// src/components/InboxScreen.vue
<template>
  <div>
    <div v-if="isError" class="page lists-show">
      <div class="wrapper-message">
        <span class="icon-face-sad" />
        <p class="title-message">Oh no!</p>
        <p class="subtitle-message">Something went wrong</p>
      </div>
    </div>
    <div v-else class="page lists-show">
      <nav>
        <h1 class="title-page">Taskbox</h1>
      </nav>
      <TaskList />
    </div>
  </div>
</template>
<script lang="ts" setup>
import { computed } from 'vue'

import { useTaskStore } from '../store'

import TaskList from './TaskList.vue'

//👇 Creates a store instance
const store = useTaskStore()
// 👇 Fetches tasks for the store
store.fetchTasks()

//👇 Retrieves the error from the store's state
const isError = computed(() => store.status === 'failed')
</script>
